quarkus.otel.logs.enabled=true
quarkus.application.name=ms-event-adapter
quarkus.otel.exporter.otlp.logs.endpoint=https://otlp-gateway-prod-us-east-0.grafana.net/otlp
quarkus.otel.exporter.otlp.logs.headers=aAuthorization=Basic%20NzEyNzgyOmdsY19leUp2SWpvaU9URTROakF3SWl3aWJpSTZJbTF6TFdWMlpXNTBMV0ZrWVhCMFpYSWlMQ0pySWpvaVlUaG9VVEYwVkRaRk1HbHphamc0TWtsWE4xZEVPREpTSWl3aWJTSTZleUp5SWpvaWNISnZaQzExY3kxbFlYTjBMVEFpZlgwPQ==