# 1. Habilitar OTLP
quarkus.otel.logs.enabled=true
quarkus.otel.metrics.enabled=true
quarkus.otel.traces.enabled=true

# 2. Configurar el Endpoint local (Alloy)
# Importante: Usamos el nombre 'alloy' que Railway te confirmó
quarkus.otel.exporter.otlp.endpoint=http://alloy.railway.internal:4317
quarkus.otel.exporter.otlp.protocol=grpc
# Endpoint para Micrometer OTLP (HTTP) — necesita su propia config
quarkus.micrometer.export.otlp.url=http://alloy.railway.internal:4318/v1/metrics
quarkus.application.name=ms-event-adapter

# Limitar el muestreo de trazas al 10%

# O mejor aún, usa el ratio directo:
quarkus.otel.traces.sampler=traceidratio
quarkus.otel.traces.sampler.arg=0.1