# 1. Habilitar OTLP
quarkus.otel.logs.enabled=true
quarkus.otel.metrics.enabled=true
quarkus.otel.traces.enabled=true

# 2. Configurar el Endpoint local (Alloy)
# Importante: Usamos el nombre 'alloy' que Railway te confirmó
quarkus.otel.exporter.otlp.endpoint=http://alloy:4317

# 3. Protocolo y Servicio
quarkus.otel.exporter.otlp.protocol=grpc
quarkus.application.name=ms-event-adapter

# Limitar el muestreo de trazas al 10%
quarkus.otel.bsp.schedule-delay=10s
quarkus.otel.traces.sampler=parentbased_always_off
# O mejor aún, usa el ratio directo:
quarkus.otel.traces.sampler=traceidratio
quarkus.otel.traces.sampler.arg=0.1